cv_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("opencv_webapp.urls")),
]

opencv_webapp/urls.py
from django.urls import path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "opencv_webapp"

urlpatterns = [
    path("", views.first_view, name="first_view"),  # 127.0.0.1:8000
    path("simple_upload/", views.simple_upload, name="simple_upload"),
    path('detect_face/', views.detect_face, name='detect_face'),
]

# MEDIA_URL 은 위의 urlpattern에 추가
# document_root 는 실제로 파일이 존재하는 위치
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

opencv_webapp/models.py
from django.db import models


# Create your models here.
class ImageUploadModel(models.Model):
    # blank=True : Form에서 빈 채로 저장되는 것을 허용 (views.py에서 활용한 .is_valid() 함수가 검증 진행 시)
    description = models.CharField(max_length=255, blank=True)
    # upload_to : 저장될 파일의 경로를 지정 (ex. ‘images/2020/02/21/test_image.jpg’)
    document = models.ImageField(upload_to="images/%Y/%m/%d")
    # auto_now_add : 자동으로 저장되는 시점을 기준으로 현재 시간을 세팅
    uploaded_at = models.DateTimeField(auto_now_add=True)

opencv_webapp/forms.py
from django import forms
from .models import ImageUploadModel


class SimpleUploadForm(forms.Form):
    title = forms.CharField(max_length=50)
    
    # ImageField Inherits all attributes and methods from FileField, but also validates that the uploaded object is a valid image.
    # file = forms.FileField()
    image = forms.ImageField() # ImageField는 FileField를 상속받아서 이미지인지 체크하고 이미지만 받음.

class ImageUploadForm(forms.ModelForm):
    # form을 통해 받아야하는 데이터 (db테이블 연결)
    class Meta:
        model = ImageUploadModel
        fields = ("description","document") #uploaded_at

opencv_webapp/views.py
from django.shortcuts import render, redirect
from .forms import SimpleUploadForm, ImageUploadForm
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from .cv_functions import cv_detect_face 


def first_view(request):
    return render(request, "opencv_webapp/first_view.html", {})


def simple_upload(request):
    if request.method == "POST":
        # print(request.POST) : <QueryDict: {'csrfmiddlewaretoken': [‘~~~’], 'title': ['upload_1']}>
        # print(request.FILES) : <MultiValueDict: {'image': [<InMemoryUploadedFile: ses.jpg (image/jpeg)>]}>
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = SimpleUploadForm(request.POST, request.FILES)

        if form.is_valid():
            myfile = request.FILES["image"]  # 메모리에 한시적으로 저장되어있는 파일 객체
            fs = FileSystemStorage()

            # myfile.name : 'ses.jpg' (사용자가 업로드한 파일 원본의 이름)
            # filename : 'ses_cKWh3Mj.jpg' (서버에 업로드가 끝난 파일의 이름, 중복될 시 자동으로 변경됨)
            # 서버에 업로드가 끝난 이미지 파일의 URL을 얻어내 Template에게 전달

            filename = fs.save(myfile.name, myfile)  # 저장이 완료 된 파일의 이름
            uploaded_file_url = fs.url(
                filename
            )  # 저장이 완료 된 파일로 접근 가능한 URL // # '/media/ses.jpg'

            # fs.save() - fs저장 / fs.url() - 저장 끝난 파일을 접근 가능한 url 얻어내는것 / fs.delete() - fs 파일 삭제

            context = {
                "form": form,
                "uploaded_file_url": uploaded_file_url,
            }  # filled form
            return render(request, "opencv_webapp/simple_upload.html", context)

    else:  # request.method == 'GET'
        form = SimpleUploadForm()
        context = {"form": form}  # 비어있는 form 을 보여줌
        return render(request, "opencv_webapp/simple_upload.html", context)


def detect_face(request):
    if request.method == "POST":
        # 비어있는 Form에 사용자가 업로드한 데이터를 넣고 검증합니다.
        form = ImageUploadForm(request.POST, request.FILES)  # filled form
        if form.is_valid():
            post = form.save(commit=False)
            # save() 함수는 DB에 저장될 ImageUploadModel 클래스 객체 자체를 리턴함 (== record 1건)
            # Form에 채워진 데이터를 DB에 실제로 저장하기 전에 변경/추가할 수 있음 (commit=False)
            # ex) post.description = papago.translate(post.description)
            post.save()  # Form 객체('form')에 채워져 있는 데이터를 DB에 실제로 저장

            # document : ImageUploadModel Class에 선언되어 있는 “document”에 해당
            imageURL = settings.MEDIA_URL + form.instance.document.name
            # == form.instance.document.url
            # == post.document.url
            # == '/media/images/2021/10/29/ses_XQAftn4.jpg'
            # print(form.instance, form.instance.document.name, form.instance.document.url)
            cv_detect_face(settings.MEDIA_ROOT_URL + imageURL) # 추후 구현 예정

            return render(
                request, "opencv_webapp/detect_face.html", {"form": form, "post": post}
            )

    else:
        form = ImageUploadForm()  # empty form
        return render(request, "opencv_webapp/detect_face.html", {"form": form})

opencv_webapp/templates/opencv_webapp/detect_face.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
    <title>Opencv-Django</title>
    </head>
    <body>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
        {% if post %}
        <!-- post.document : ImageUploadModel Class에 선언되어 있는 "document"에 해당 (브라우저 확인) -->
        <img src="{{ post.document.url }}">
        <p>Uploaded file @ : <a href="{{ post.document.url }}">{{ post.document }}</a></p>
        {% endif %}
        <p>
            <a href="{% url 'opencv_webapp:detect_face' %}">Return to home</a>
        </p>
    </body>
</html>

opencv_webapp/templates/opencv_webapp/first_view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Opencv-Django</title>
    </head>
    <body>
        Hello world!
    </body>
</html>

opencv_webapp/templates/opencv_webapp/simple_upload.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Opencv-Django</title>
    </head>
    <body>
        <h1>Upload your image file.</h1>
        <form method="POST" enctype="multipart/form-data">
            <!-- enctype : encoding type // form 사용 시 항상 넣어줘야함-->
            {% csrf_token %}
            <!-- form.ap_p : input tag들을 만들어 줌 -->
            {{ form.as_p }}
            <button type="submit">Upload</button>
        </form>
        
        <!-- post 요청이 처리 된 후에 user에게 결과를 보여줄 때 유저에게 결과를 보여줄 때 업로드가 완료 된 이미지파일을 보여주고, 그 이미지파일에 접근 가능한 url을 적기 위해 적음 -->
        {% if uploaded_file_url %}
        <img src="{{ uploaded_file_url }}">
        <p> <!-- 이미지로 접근 가능한 url을 가져와서 이미지를 보여줄 때 사용, a태그 만들때도 사용 -->
            Uploaded file @ : <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a> 
        </p>
    {% endif %}
    
    <!-- 모든게 끝난 후 simple_upload 페이지로 redirect -->
    <p><a href="{% url 'opencv_webapp:simple_upload' %}">Return to home</a></p>
</body>
</html>